/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
// tslint:disable:no-mixed-interface

export interface PropertyLayer {
  property: string;
  label: string;
}

export interface MultiSeries {
  aggregation_name: string
  colour?: string
}


export interface ChartConfig {
  // id is required for all
  id: string;
  style: {
    // need to check if full or something else
    height_constraint: 'none' | 'full',
    width_constraint: 'half' | 'full'
  };
  options: {
    chart_type: 'bar' | 'line' | 'line' | 'pie',
    title?: string,
    text?: string,
    layout?: {
      showlegend?:  boolean,
      title: string,
      yaxis?: {
        title: string,
      },
      xaxis?: {
        title: string,
      },
      barmode?: 'stack'
    },
    cumulative?: boolean,
    time_series?: boolean,
    bin_by?: string,
    geographic_level_refactor_this_key_name?: string,
    multi_series?: MultiSeries[]
    single_series?: {
      aggregation_name: string
    }
    generate_series_from?: string,
  };
}

/**
 * The configuration for the IRS Monitor applet for douma
 */
export interface IrsMonitor {
  /**
   * The title for the applet
   */
  title?: string;

  /**
   * The icon for the applet
   */
  icon?: string;

  /**
   * The start of the current season
   */
  season_start_dates: string[];
  /**
   * Map configuration
   */
  map: {
    chart_type: "map";
    bin_by: string;
    aggregation_names: string[];
    response_point_fields: string[];
    property_layers: PropertyLayer[];
  };
  /**
   * Table configuration
   */
  table: {
    chart_type: "table";
    bin_by: string;
    aggregation_names: string[];
    property_layers: PropertyLayer[];
  };
  charts?: ChartConfig[];
}
